version: '3'
services:
  aluraflix-api:
    image: 'aluraflix-api:latest'
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db_aluraflix'
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: